---

  - name: Install packages to install android sdk
    apt: name={{ item }} state=installed
    with_items:
      - libncurses5
      - libstdc++6
      - zlib1g
      - imagemagick
      - expect
      - gradle
      - ant
      - ccache
      - autoconf
      - automake
      - ant
      - ccache
      - python-dev
      - zlibc
      - libsane

  - name: Download sdk tools
    get_url: >
     url=http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
     dest=/opt/android-sdk_r23.0.2-linux.tar.gz
    register: sdk_file

  - name: Unarchive sdk tools
    command: >
     tar xzf {{ sdk_file.dest }}
     creates=/opt/android-sdk-linux
     chdir=/opt

  - name: Set envs for android sdk
    shell: 'echo "export PATH=/opt/android-sdk-linux/tools:${PATH}" >> $HOME/.bash_profile'

  - name: Install Android SDKs
    shell: echo y | android update sdk -u -a -t "{{ item }}"
    with_items:
     - tools
     - platform-tools
     - build-tools-19.1.0
     - android-20
     - android-19
     - android-18
     - android-17
     - extra-android-support
